### ISSUE TITLE
[To Do] Board - Changes to the wiki content (please add to this comment things that need to be changed)

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/wiki#1020]
- [ ] Add `details` to tables with a lot of content to reduce page scroll.
- - [ ] `item_template`
- - [ ]  `map`
- - [ ]  `chrclasses`
- - [ ]  `chrraces`
- - [ ]  `smart_scripts`
- - [ ] ` ItemLimitCategory.dbc` ( https://github.com/azerothcore/wiki/issues/854 )
- [ ] Update `SkillLine.dbc` to match the standard wiki.
- [ ] Update `Spell.dbc` to match the standard wiki.
- [ ] Add DBC content with `details`
- [ ] Adding Headers for the Instalation Pages (Windows, Linux, Mac) for easier navigation within the page
- [ ] Update Instalation Requirements Pages for Mac and Linux to match the new `bs-callout-info` that appears on Windows 
- [ ] Update Core Instalation for Windows to add the same `bs-callout-info` Requirements instead of a redirect.
- [ ] Windows Requirements  add a  "note" warning to step 8. boost `Important is to use '/', not '\' when pointing to the directory. (Make sure that it does not have a trailing slash (end of the path). If you still get problems, add the same variable in the USER variables section too, as shown in the image below.)`
- [ ] Figure out what to do with `update` page ( https://github.com/azerothcore/wiki/issues/845 )
- [ ] Add/Update CMAKE Hooks Page (https://github.com/azerothcore/wiki/issues/177)
- [ ] Add/Update BASH Hooks Page ( https://github.com/azerothcore/wiki/issues/176 )
- [ ] Correct `hooks-script` referenced in `the-modular-structure` using the wrong link `Hooks-Script`
- [ ] Update `installing-a-module` to be less vague and importants notes. Like copying the module config and changing the copy's exntetion to not have .dist 
- [ ] Informative page about which things like tables or friends require a client clear cache ( https://github.com/azerothcore/wiki/issues/863 )
- [ ] Create `WorldMapArea.dbc`
- [ ] Update `quest_poi` fields and may a image reference for ObjectiveIndex like `quest_poi_points`
- [ ] Update `points_of_interest` fields and explanation if.
- [ ] GM commands could be divided per catergory under the a header
