### ISSUE TITLE
[TODO]: Implement documentation for new SAI target types

### ISSUE THREAD

**Issue by Gultask** [azerothcore/wiki#881]
### Is your feature request related to a problem? Please describe.

- [ ] SMART_ACTION_SET_CORPSE_DELAY
- [ ] SMART_ACTION_DISABLE_EVADE
- [ ] SMART_ACTION_GO_SET_GO_STATE
- [ ] SMART_ACTION_SET_CAN_FLY

### Describe the solution you'd like

.

### Describe alternatives you've considered

.
